### ISSUE TITLE
v0.7.0 throws Error-  Could not find matching container path in the binds: [/blog-example-code/testcontainers-cypress-example/target/test-classes/e2e/:/e2e:rw]

### ISSUE THREAD

**Issue by vikikamath** [wimdeblauwe/testcontainers-cypress#17]
the [testcontainers-cypress-example](https://github.com/wimdeblauwe/blog-example-code/blob/master/testcontainers-cypress-example/pom.xml) works with earlier versions ... but, when I switch to latest version v0.7.0 it seems to error out with following error message

```
/blog-example-code/testcontainers-cypress-example/target/test-classes/e2e/:/e2e:rw]
        at io.github.wimdeblauwe.testcontainers.cypress.CypressContainer.getReportsPathInContainer(CypressContainer.java:296) ~[testcontainers-cypress-0.7.0.jar:na]
        at io.github.wimdeblauwe.testcontainers.cypress.CypressContainer.buildEntryPoint(CypressContainer.java:268) ~[testcontainers-cypress-0.7.0.jar:na]
        at io.github.wimdeblauwe.testcontainers.cypress.CypressContainer.lambda$configure$0(CypressContainer.java:58) ~[testcontainers-cypress-0.7.0.jar:na]
        at org.testcontainers.containers.GenericContainer.lambda$applyConfiguration$16(GenericContainer.java:814) ~[testcontainers-1.14.1.jar:na]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
        at org.testcontainers.containers.GenericContainer.applyConfiguration(GenericContainer.java:814) ~[testcontainers-1.14.1.jar:na]
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:349) ~[testcontainers-1.14.1.jar:na]
        at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:315) ~[testcontainers-1.14.1.jar:na]
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) ~[duct-tape-1.0.8.jar:na]
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:313) ~[testcontainers-1.14.1.jar:na]
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:300) ~[testcontainers-1.14.1.jar:na]
        at io.github.wimdeblauwe.testcontainers.cypress.CypressContainer.start(CypressContainer.java:63) ~[testcontainers-cypress-0.7.0.jar:na]
        at com.wimdeblauwe.examples.testcontainerscypressexample.todo.web.TodoControllerCypressIntegrationTest.runCypressTests(TodoControllerCypressIntegrationTest.java:26) ~[test-classes/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675) ~[junit-platform-commons-1.5.2.jar:1.5.2]
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60) ~[junit-jupiter-engine-5.5.2.jar:5.5.2]
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:125) ~[junit-jupiter-engine-5.5.2.jar:5.5.2]
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:132) ~[junit-jupiter-engine-5.5.2.jar:5.5.2]
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:124) ~[junit-jupiter-engine-5.5.2.jar:5.5.2]
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:74) ~[junit-jupiter-engine-5.5.2.jar:5.5.2]
        at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115) ~[junit-jupiter-engine-5.5.2.jar:5.5.2]
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105) ~[junit-jupiter-engine-5.5.2.jar:5.5.2]
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:104) ~[junit-jupiter-engine-5.5.2.jar:5.5.2]
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:62) ~[junit-jupiter-engine-5.5.2.jar:5.5.2]
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:43) ~[junit-jupiter-engine-5.5.2.jar:5.5.2]
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:35) ~[junit-jupiter-engine-5.5.2.jar:5.5.2]
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104) ~[junit-jupiter-engine-5.5.2.jar:5.5.2]
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98) ~[junit-jupiter-engine-5.5.2.jar:5.5.2]
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:202) ~[junit-jupiter-engine-5.5.2.jar:5.5.2]
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:198) ~[junit-jupiter-engine-5.5.2.jar:5.5.2]
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135) ~[junit-jupiter-engine-5.5.2.jar:5.5.2]
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69) ~[junit-jupiter-engine-5.5.2.jar:5.5.2]
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540) ~[na:na]
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540) ~[na:na]
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51) ~[junit-platform-engine-1.5.2.jar:1.5.2]
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220) ~[junit-platform-launcher-1.3.1.jar:1.3.1]
        at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188) ~[junit-platform-launcher-1.3.1.jar:1.3.1]
        at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202) ~[junit-platform-launcher-1.3.1.jar:1.3.1]
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181) ~[junit-platform-launcher-1.3.1.jar:1.3.1]
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128) ~[junit-platform-launcher-1.3.1.jar:1.3.1]
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150) ~[surefire-junit-platform-2.22.2.jar:2.22.2]
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124) ~[surefire-junit-platform-2.22.2.jar:2.22.2]
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384) ~[surefire-booter-2.22.2.jar:2.22.2]
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345) ~[surefire-booter-2.22.2.jar:2.22.2]
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126) ~[surefire-booter-2.22.2.jar:2.22.2]
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418) ~[surefire-booter-2.22.2.jar:2.22.2]

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.501 s <<< FAILURE! - in com.wimdeblauwe.examples.testcontainerscypressexample.todo.web.TodoControllerCypressIntegrationTest
[ERROR] runCypressTests  Time elapsed: 3.367 s  <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup failed
        at com.wimdeblauwe.examples.testcontainerscypressexample.todo.web.TodoControllerCypressIntegrationTest.runCypressTests(TodoControllerCypressIntegrationTest.java:26)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
        at com.wimdeblauwe.examples.testcontainerscypressexample.todo.web.TodoControllerCypressIntegrationTest.runCypressTests(TodoControllerCypressIntegrationTest.java:26)
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
        at com.wimdeblauwe.examples.testcontainerscypressexample.todo.web.TodoControllerCypressIntegrationTest.runCypressTests(TodoControllerCypressIntegrationTest.java:26)
Caused by: java.lang.IllegalArgumentException: Could not find matching container path in the binds: [C:/Users/kamatv/Code/test-containers-examples/blog-example-code/testcontainers-cypress-example/target/test-classes/e2e/:/e2e:rw]
        at com.wimdeblauwe.examples.testcontainerscypressexample.todo.web.TodoControllerCypressIntegrationTest.runCypressTests(TodoControllerCypressIntegrationTest.java:26)

```

**Comment by vikikamath** [comment]
`0.4.0` is the last working version for me.

**Comment by wimdeblauwe** [comment]
Did you do a `mvn clean test`? When I tried it, it works fine. I have now committed an update to `0.7.0`, see https://github.com/wimdeblauwe/blog-example-code/commit/f9ce7dd901b185f5a84040b4ab481002d0cc33fa

**Comment by vikikamath** [comment]
weird I took your update and ran `mvn clean test` still getting same error:

```
// target/surefire-reports/....
-------------------------------------------------------------------------------
Test set: com.wimdeblauwe.examples.testcontainerscypressexample.todo.web.TodoControllerCypressIntegrationTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.703 s <<< FAILURE! - in com.wimdeblauwe.examples.testcontainerscypressexample.todo.web.TodoControllerCypressIntegrationTest
runCypressTests  Time elapsed: 3.499 s  <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at com.wimdeblauwe.examples.testcontainerscypressexample.todo.web.TodoControllerCypressIntegrationTest.runCypressTests(TodoControllerCypressIntegrationTest.java:26)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at com.wimdeblauwe.examples.testcontainerscypressexample.todo.web.TodoControllerCypressIntegrationTest.runCypressTests(TodoControllerCypressIntegrationTest.java:26)
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at com.wimdeblauwe.examples.testcontainerscypressexample.todo.web.TodoControllerCypressIntegrationTest.runCypressTests(TodoControllerCypressIntegrationTest.java:26)
Caused by: java.lang.IllegalArgumentException: Could not find matching container path in the binds: [C:/Users/kamatv/Code/test-containers-examples/blog-example-code/testcontainers-cypress-example/target/test-classes/e2e/:/e2e:rw]
	at com.wimdeblauwe.examples.testcontainerscypressexample.todo.web.TodoControllerCypressIntegrationTest.runCypressTests(TodoControllerCypressIntegrationTest.java:26)
```
I'll check again to see if I missed anything.

**Comment by imgruntw** [comment]
this bug can be fixed in `com.senec.pip.e2e.container.CypressContainer#getReportsPathInContainer` in line 290 with: 
`String path = FilenameUtils.separatorsToSystem(bind.getPath());`

**Comment by wimdeblauwe** [comment]
@imgruntw Do you mean to use https://commons.apache.org/proper/commons-io/javadocs/api-release/org/apache/commons/io/FilenameUtils.html#separatorsToSystem-java.lang.String- ? Would hate to add a dependency to commons-io just for this. 

Where do you get the `com.senec.pip.e2e.container` package? The normal package is `io.github.wimdeblauwe.testcontainers.cypress`.

**Comment by wimdeblauwe** [comment]
@vikikamath Are you running on Windows?

**Comment by vikikamath** [comment]
Confirming version 1.0.0 fixes it ... thanks! this was run on Windows 10.

**Comment by atomfrede** [comment]
Sorry reviving this issue. I am right now reading your book @wimdeblauwe (and it is really great, thanks for that). Right now I am trying to integrate cypress testcontainers with gradle. I have the same issue with `Could not find matching container path in the binds: [/home/fhahne/git/gitlab.com/XX/YY/ZZ/build/classes/java/test/e2e/:/e2e:rw]`. I am not sure what the problem might be. Am I right that the integration test sources should be mounted to the container?

**Comment by wimdeblauwe** [comment]
Please create a separate issue, but I have no clue what might the problem to be honest.

**Comment by atomfrede** [comment]
Will do and provide a minimal example to ensure its not related to my environment.

**Comment by deen13** [comment]
This error happened to me when I did not use any TestResultStrategy so that the report path was  `/home/deen/code/prodzilla/backend/target/test-classes/e2e/cypress/reports/mochawesome` instead of `/home/deen/code/prodzilla/backend/build/resources/test/e2e/cypress/reports/mochawesome`.

The fix for me was: 
```
val gradleTestResultStrategy = MochawesomeGatherTestResultsStrategy(
    FileSystems.getDefault().getPath("build", "resources", "test", "e2e", "cypress", "reports", "mochawesome")
)

CypressContainer().withGatherTestResultsStrategy(gradleTestResultStrategy)
```

**Comment by atomfrede** [comment]
Like in the documentation? https://github.com/wimdeblauwe/testcontainers-cypress#gradle :D
